server.port=8803

# URL do User Service para validacao de usuarios, etc.
userservice.api.url=http://user-service:8802

# Chave interna para comunicacao segura entre servicos
api.internal.secret=MinhaChaveSecretaSuperSeguraParaTestesLocais123!

# Configuracoes JWT para autenticacao
jwt.secret.key=SuaChaveJWTSuperLongaESeguraGeradaEmBase64ParaTestesLocais123456789=
jwt.expiration.ms=900000

# ===============================================
# OBSERVABILIDADE E MONITORAMENTO
# ===============================================
management.observations.key-values.application=${spring.application.name}
management.metrics.tags.application=${spring.application.name}
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# CONFIGURACAO DE SEGURANCA PARA O ACTUATOR (PARA PROMETHEUS)
# Permite acesso publico ao endpoint /actuator/prometheus para coleta de metricas
spring.security.web.publish-digest-only=true
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true

management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans