# Porta do servico
server.port=8805

# ===============================================
# BANCO DE DADOS POSTGRESQL (REDE DOCKER)
# ===============================================
# Aponta para o SEU banco de dados ('postgres-feedback-db')
spring.datasource.url=jdbc:postgresql://postgres-feedback-db:5432/feedback_service_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update



# ===============================================
# URLs DOS MICROSSERVICOS (REDE DOCKER)
# ===============================================
# Aponta para o user-service para buscar detalhes dos usuarios
userservice.api.url=http://user-service:8802

# ===============================================
# SEGREDOS
# ===============================================
api.internal.secret=MinhaChaveSecretaSuperSeguraParaTestesLocais123!

# ===============================================
# MONITORAMENTO
# ===============================================
management.endpoints.web.exposure.include=health,prometheus