# Define a porta principal da aplicacao
server.port=8080

# ===============================================
# SEGREDOS (DEFINIDOS LOCALMENTE PARA TESTES)
# ===============================================
api.internal.secret=MinhaChaveSecretaSuperSeguraParaTestesLocais123!
jwt.secret.key=SuaChaveJWTSuperLongaESeguraGeradaEmBase64ParaTestesLocais123456789=

# ===============================================
# OBSERVABILIDADE E MONITORAMENTO
# ===============================================

# Adiciona uma tag 'application' em todas as metricas, facilitando a filtragem no Grafana.
management.metrics.tags.application=api-gateway

# Ativa o rastreamento distribuido (tracing) para seguir requisicoes entre servicos.
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# Adiciona o Trace ID e Span ID ao padrao de log para correlacionar logs entre servicos.
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]


# CONFIGURACAO DE SEGURANCA PARA O ACTUATOR (PARA PROMETHEUS)
# Permite acesso publico ao endpoint /actuator/prometheus para coleta de metricas
spring.security.web.publish-digest-only=true
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true

# Desabilita a autenticacao padrao do Spring Security para o Actuator
# IMPORTANTISSIMO para que o Prometheus possa acessar sem 401/403
spring.security.web.reactive.filter.url.enabled=false
spring.security.filter.enabled=false
spring.autoconfigure.exclude[0]=org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration

management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# ===============================================
# CONFIGURACAO DO SERVICE DISCOVERY (EUREKA)
# ===============================================
# Define o nome que este servico tera no Eureka
spring.application.name=api-gateway

# Endereco do Servidor Eureka (dentro da rede Docker)
eureka.client.service-url.defaultZone=http://eureka:8761/eureka/

# Informa ao Gateway que ele deve usar o Eureka para encontrar outros servicos
spring.cloud.gateway.discovery.locator.enabled=true