# Define a porta principal da aplicacao
server.port=8080

# ===============================================
# URLs DOS MICROSSERVICOS (REDE DOCKER)
# ===============================================
service.auth.url=http://auth-service:8803
service.user.url=http://user-service:8802
service.processfeedback.url=http://processador-feedbacks:8804
service.feedback.url=http://feedback-service:8805

# ===============================================
# SEGREDOS (DEFINIDOS LOCALMENTE PARA TESTES)
# ===============================================
api.internal.secret=MinhaChaveSecretaSuperSeguraParaTestesLocais123!
jwt.secret.key=SuaChaveJWTSuperLongaESeguraGeradaEmBase64ParaTestesLocais123456789=

# ===============================================
# OBSERVABILIDADE E MONITORAMENTO
# ===============================================
# Expoe os endpoints de saude (health) e metricas (prometheus) via web.
management.endpoints.web.exposure.include=health,prometheus

# Adiciona uma tag 'application' em todas as metricas, facilitando a filtragem no Grafana.
management.metrics.tags.application=api-gateway

# Ativa o rastreamento distribuido (tracing) para seguir requisicoes entre servicos.
management.tracing.enabled=true
management.tracing.sampling.probability=1.0 # Rastreia 100% das requisicoes (bom para desenvolvimento)

# Adiciona o Trace ID e Span ID ao padrao de log para correlacionar logs entre servicos.
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]