# Define a porta que o Gateway usara na sua maquina
server.port=8080

# ===============================================
# URLs DOS MICROSSERVICOS (REDE DOCKER)
# ===============================================
# Aponta para o nome do servico 'auth-service' e sua porta interna no Docker
service.auth.url=http://auth-service:8803
# Aponta para o nome do servico 'user-service' e sua porta interna no Docker
service.user.url=http://user-service:8802
# Aponta para o nome do servico 'processador-feedbacks' e sua porta interna no Docker
service.processfeedback.url=http://processador-feedbacks:8804
# Aponta para o nome do servico 'feedback-service' e sua porta interna no Docker
service.feedback.url=http://feedback-service:8805

# ===============================================
# SEGREDOS (DEFINIDOS LOCALMENTE PARA TESTES)
# ===============================================
# Chave secreta para comunicacao interna (deve ser a mesma em todos os servicos)
api.internal.secret=MinhaChaveSecretaSuperSeguraParaTestesLocais123!
# Chave para assinar os tokens JWT (deve ser a mesma do auth-service)
jwt.secret.key=SuaChaveJWTSuperLongaESeguraGeradaEmBase64ParaTestesLocais123456789=

# ===============================================
# MONITORAMENTO
# ===============================================
management.endpoints.web.exposure.include=health,prometheus