# Porta do servico
server.port=8804

# Aponta para o RabbitMQ na rede Docker
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Chave secreta para comunicacao interna
api.internal.secret=MinhaChaveSecretaSuperSeguraParaTestesLocais123!

# Configuracao de monitoramento
management.endpoints.web.exposure.include=health,prometheus