# Porta do servico (para o health check do Docker)
server.port=8806

# ===============================================
# RABBITMQ (REDE DOCKER)
# ===============================================
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ===============================================
# E-mail (Brevo)
# ===============================================
# Cole suas chaves reais aqui para o teste local
brevo.api.key=SUA_CHAVE_DE_API_DO_BREVO_AQUI
brevo.sender.email=seu-email-verificado@brunofragadev.com

# ===============================================
# MONITORAMENTO
# ===============================================
management.endpoints.web.exposure.include=health,prometheus