# Define a porta que o servico usara dentro do Docker
server.port=8802

# ===============================================
# BANCO DE DADOS POSTGRESQL (REDE DOCKER)
# ===============================================
# A URL aponta para o nome do container do banco ('postgres-user-db') e a porta padrao 5432
spring.datasource.url=jdbc:postgresql://postgres-user-db:5432/user_service_db
# Credenciais que definiremos no docker-compose.yml para este banco
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update # 'update' e bom para desenvolvimento local

# ===============================================
# RABBITMQ (REDE DOCKER)
# ===============================================
# Aponta para o nome do container do RabbitMQ ('rabbitmq')
spring.rabbitmq.host=rabbitmq
# Credenciais padrao do RabbitMQ no Docker
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ===============================================
# SEGREDOS
# ===============================================
# Chave secreta para comunicacao interna (deve ser a mesma do Gateway)
api.internal.secret=MinhaChaveSecretaSuperSeguraParaTestesLocais123!

# ===============================================
# MONITORAMENTO
# ===============================================
management.endpoints.web.exposure.include=health,prometheus