server.port=8804

# Chave interna para comunicacao segura entre servicos
api.internal.secret=MinhaChaveSecretaSuperSeguraParaTestesLocais123!

# Configuracoes RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

# ===============================================
# OBSERVABILIDADE E MONITORAMENTO
# ===============================================
management.endpoints.web.exposure.include=health,prometheus
management.observations.key-values.application=${spring.application.name}
management.metrics.tags.application=${spring.application.name}
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# CONFIGURACAO DE SEGURANCA PARA O ACTUATOR (PARA PROMETHEUS)
# Permite acesso publico ao endpoint /actuator/prometheus para coleta de metricas
spring.security.web.publish-digest-only=true
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true

management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

# CONFIGURACAO DO SERVICE DISCOVERY (EUREKA)
# ===============================================
# Define o nome que este servico tera no Eureka
spring.application.name=processador-feedbacks

# Endereco do Servidor Eureka (dentro da rede Docker)
eureka.client.service-url.defaultZone=http://eureka:8761/eureka/