# Porta do servico
server.port=8804


# Chave secreta para comunicacao interna
api.internal.secret=MinhaChaveSecretaSuperSeguraParaTestesLocais123!

# Configuracao de monitoramento
management.endpoints.web.exposure.include=health,prometheus