server.port=8806

# Chave de API Brevo (Sendinblue) para envio de e-mails
brevo.api.key=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
brevo.sender.email=brunofragaa97@gmail.com

# ===============================================
# OBSERVABILIDADE E MONITORAMENTO
# ===============================================
management.endpoints.web.exposure.include=health,prometheus
management.observations.key-values.application=${spring.application.name}
management.metrics.tags.application=${spring.application.name}
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans