# Porta do servico (para o health check do Docker)
server.port=8806

# ===============================================
# E-mail (Brevo)
# ===============================================
# Cole suas chaves reais aqui para o teste local
brevo.api.key=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
brevo.sender.email=brunofragaa97@gmail.com

# ===============================================
# MONITORAMENTO
# ===============================================
management.endpoints.web.exposure.include=health,prometheus