# Define a porta do servico
server.port=8803

# ===============================================
# URLs DOS MICROSSERVICOS (REDE DOCKER)
# ===============================================
# Aponta para o user-service para validar credenciais
userservice.api.url=http://user-service:8802

# ===============================================
# SEGREDOS
# ===============================================
# Chave secreta para comunicacao interna (deve ser a mesma do Gateway)
api.internal.secret=MinhaChaveSecretaSuperSeguraParaTestesLocais123!
# Chave para assinar os tokens JWT (deve ser a mesma do Gateway)
jwt.secret.key=SuaChaveJWTSuperLongaESeguraGeradaEmBase64ParaTestesLocais123456789=
jwt.expiration.ms=900000

# ===============================================
# MONITORAMENTO
# ===============================================
management.endpoints.web.exposure.include=health,prometheus